package com.nldining.app.models.enums

enum class Category(val displayName: String) {
    GEEN_VOORKEUR("Geen voorkeur"),
    INDISCH("Indiaas"),
    TURKS("Turks"),
    INTERNATIONAAL("Internationaal"),
    FUSION("Fusion"),
    GRIEKS("Grieks"),
    HOLLANDS("Hollands"),
    CHINEES("Chinees"),
    FRANS("Frans"),
    AZIATISCH("Aziatisch"),
    JAPANS("Japans"),
    VEGETARISCH("Vegetarisch"),
    BBQ_GRILL("BBQ/Grill"),
    MEDITERRAANS("Mediterraans"),
    SPAANS("Spaans"),
    REGIONAAL("Regionaal"),
    EUROPEES("Europees"),
    ITALIAANS("Italiaans"),
    THAIS("Thais"),
    PANNENKOEKEN("Pannenkoeken"),
    PIZZERIA("Pizzeria"),
    ARABISCH("Arabisch"),
    SURINAAMS("Surinaams"),
    BIOLOGISCH("Biologisch"),
    ETHIOPISCH("Ethiopisch"),
    INDONESISCH("Indonesisch"),
    PORTUGEES("Portugees"),
    CARIBISCH("Caribisch"),
    BRAZILIAANS("Braziliaans"),
    PERUAANS("Peruaans"),
    VIS("Vis"),
    ARGENTIJNS("Argentijns"),
    MEXICAANS("Mexicaans"),
    EGYPTISCH("Egyptisch"),
    VEGANISTISCH("Veganistisch"),
    BRASSERIE("Brasserie"),
    AMERIKAANS("Amerikaans"),
    AFRIKAANS("Afrikaans"),
    SCANDINAVISCH("Scandinavisch"),
    MAROKKAANS("Marokkaans"),
    LIBANEES("Libanees"),
    ENGELS("Engels"),
    VIETNAMEES("Vietnamees"),
    SYRISCH("Syrisch"),
    BELGISCH("Belgisch"),
    KOREAANS("Koreaans"),
    AUSTRALISCH("Australisch"),
    OOST_EUROPEES("Oost-Europees"),
    DUITS("Duits"),
    CUBAANS("Cubaans"),
    PAKISTAANS("Pakistaans"),
    KENIAANS("Keniaans"),
    PALESTIJNS("Palestijns"),
    AFGHAANS("Afghaans"),
    STEAKHOUSE("Steakhouse"),
    IRAANS("Iranees"),
    TUNESISCH("Tunesisch"),
    COLOMBIAANS("Colombiaans"),
    CANADEES("Canadees"),
    OOSTENRIJKS("Oostenrijks"),
    SCHOTS("Schots"),
    ZWITSERS("Zwitsers"),
    BISTRO("Bistro"),
    WIJNBAR("Wijnbar"),

    ONBEKEND("Onbekend");

    override fun toString(): String = displayName
}