package com.nldining.app.models.enums

enum class Tags(val displayName: String) {
    GEEN_VOORKEUR("Geen voorkeur"),
    ZAKENLUNCH("Zakenlunch"),
    LIVE_MUZIEK("Live muziek"),
    MET_FAMILIE("Met familie"),
    MET_VRIENDEN("Met vrienden"),
    PROVINCIE_ZUID_HOLLAND("Provincie Zuid-Holland"),
    TERRAS("Terras"),
    TUIN("Tuin"),
    AMSTERDAM_WEST("Amsterdam-West"),
    KINKERBUURT("Kinkerbuurt"),
    PROVINCIE_NOORD_HOLLAND("Provincie Noord-Holland"),
    ROMANTISCH("Romantisch"),
    AFAS_CIRCUSTHEATER("AFAS Circustheater"),
    DE_PIER("De Pier"),
    IJSSALON("IJssalon"),
    SCHEVENINGEN("Scheveningen"),
    KINDVRIENDELIJK("Kindvriendelijk"),
    PROVINCIE_GELDERLAND("Provincie Gelderland"),
    INSIDER("Insider"),
    BISTRONOMIQUE("Bistromique"),
    GAULT_MILLAU_2019("Gault&Millau 2019"),
    KERST("Kerst"),
    VALENTIJNSDAG("Valentijnsdag"),
    BISTRO("Bistro"),
    GEEN("Geen"),
    PROVINCIE_NOORD_BRABANT("Provincie Noord-Brabant"),
    AAN_HET_WATER("Aan het water"),
    GLUTENVRIJ("Glutenvrij"),
    HIGH_TEA("High tea"),
    LACTOSE_INTOLERANTIE("Lactose-intolerantie"),
    NOTENALLERGIE("Notenallergie"),
    PINDA_ALLERGIE("Pinda-allergie"),
    PROVINCIE_UTRECHT("Provincie Utrecht"),
    VEGETARISCH("Vegetarisch"),
    CERTIFICAAT_VAN_UITMUNTENDHEID_TRIPADVISOR("Certificaat van Uitmuntendheid TripAdvisor"),
    EETCAFE("Eetcafé"),
    SUSHI("Sushi"),
    BRASSERIE("Brasserie"),
    OUD_NIEUW("Oud & Nieuw"),
    VERJAARDAG("Verjaardag"),
    GROTE_MARKT_GRONINGEN("Grote Markt Groningen"),
    MARTINITOREN("Martinitoren"),
    PRINSENHOF("Prinsenhof"),
    PROVINCIE_GRONINGEN("Provincie Groningen"),
    BIOLOGISCH("Biologisch"),
    WIJNBAR("Wijnbar"),
    PROVINCIE_FRIESLAND("Provincie Friesland"),
    NIEUWMARKT("Nieuwmarkt"),
    PROVINCIE_ZEELAND("Provincie Zeeland"),
    PROVINCIE_OVERIJSSEL("Provincie Overijssel"),
    STREEKPRODUCTEN("Streekproducten"),
    PROVINCIE_LIMBURG("Provincie Limburg"),
    BURGWALLEN_OUDE_ZIJDE("Burgwallen-Oude Zijde"),
    CENTRAAL_STATION_AMSTERDAM("Centraal Station Amsterdam"),
    AMSTERDAM_ZUID("Amsterdam-Zuid"),
    BUITENVELDERT("Buitenveldert"),
    HAMBURGER("Hamburger"),
    PROVINCIE_DRENTHE("Provincie Drenthe"),
    WITTE_DE_WITHSTRAAT("Witte de Withstraat"),
    THEFORK_FESTIVAL("TheFork Festival"),
    ONZE_LIEVE_VROUWEBASILIEK("Onze Lieve Vrouwebasiliek"),
    STOKSTRAAT("Stokstraat"),
    DESSERTS("Desserts"),
    MOEDERDAG("Moederdag"),
    PASTA("Pasta"),
    PIZZA("Pizza"),
    DESIGN("Design"),
    ARCHIPELBUURT("Archipelbuurt"),
    ALL_YOU_CAN_EAT("All you can eat"),
    HELMERSBUURT("Helmersbuurt"),
    VONDELPARK("Vondelpark"),
    DE_PIJP("De Pijp"),
    TAPAS("Tapas"),
    BESTBEOORDEELD("Bestbeoordeeld"),
    HIP("Hip"),
    VEGAN("Vegan"),
    TRADITIONEEL("Traditioneel"),
    VADERDAG("Vaderdag"),
    INSIDER_TOP_2019("Insider Top 2019"),
    GASTRONOMISCH("Gastronomisch"),
    TUINWIJK("Tuinwijk"),
    HALAL("Halal"),
    OVERSCHIE_E_O("Overschie E.O."),
    GRACHTENGORDEL_ZUID("Grachtengordel-Zuid"),
    BIB_GOURMAND("Bib Gourmand"),
    NIEUWE_WERK("Nieuwe Werk"),
    ZUILEN("Zuilen"),
    DEN_BOSCH_CENTRUM("Den Bosch Centrum"),
    LEIDSEPLEIN("Leidseplein"),
    HILLEGERSBERG_SCHIEBROEK("Hillegersberg/Schiebroek"),
    JORDAAN("Jordaan"),
    BRUILOFT("Bruiloft"),
    LOOSDUINEN("Loosduinen"),
    AMSTERDAM_OOST("Amsterdam-Oost"),
    DOMTOREN("Domtoren"),
    LANGE_NIEUWSTRAAT("Lange Nieuwstraat"),
    UTRECHT_CENTRUM("Utrecht-Centrum"),
    WESTELIJK_HAVENGEBIED("Westelijk Havengebied"),
    NIEUWE_LUXOR_THEATER("Nieuwe Luxor Theater"),
    ROTTERDAM_ZUID("Rotterdam-Zuid"),
    DE_DOELEN("De Doelen"),
    ROTTERDAM_CENTRUM("Rotterdam-Centrum"),
    NEMO_SCIENCE_MUSEUM("NEMO Science Museum"),
    AMSTERDAM_NOORD("Amsterdam-Noord"),
    OP_HET_STRAND("Op het strand"),
    WATERGRAAFSMEER("Watergraafsmeer"),
    DEN_HAAG_CENTRUM("Den Haag Centrum"),
    ONE_MICHELIN_STER_2019("1 Michelin Ster 2019"),
    KATENDRECHT("Katendrecht"),
    SCHAAL_EN_SCHELPDIEREN("Schaal- en schelpdieren"),
    HERMITAGE("Hermitage"),
    OUDWIJK("Oudwijk"),
    WILHELMINAPARK("Wilhelminapark"),
    VLEES_EN_GRILLGERECHTEN("Vlees en grillgerechten"),
    DE_MARKT_MAASTRICHT("De Markt Maastricht"),
    VOGELWIJK_BOMEN_EN_VRUCHTENBUURT("Vogelwijk/Bomen- en Vruchtenbuurt"),
    INDISCHE_BUURT("Indische Buurt"),
    HET_FRONTENPARK("Het Frontenpark"),
    SINT_LAMBERTUSKERK("Sint-Lambertuskerk"),
    SINT_SERVAASBASILIEK("Sint-Servaasbasiliek"),
    UNIVERSITEIT_MAASTRICHT("Universiteit Maastricht"),
    WEST_BUITEN_RING("West (Buiten Ring)"),
    WOKKEN("Wokken"),
    RIVIERENBUURT("Rivierenbuurt"),
    KANALENEILAND("Kanaleneiland"),
    NOORDEINDE("Noordeinde"),
    ARNHEM_CENTRUM("Arnhem Centrum"),
    MARKTHAL("Markthal"),
    OUDE_HAVEN("Oude Haven"),
    KOOSJER("Koosjer"),
    MOREELSPARK("Moreelspark"),
    TIVOLIVREDENBURG("TivoliVredenburg"),
    PLEIN("Plein"),
    PROVINCIE_FLEVOLAND("Provincie Flevoland"),
    CENTRAAL_STATION_ARNHEM("Centraal Station Arnhem"),
    DE_9_STRAATJES("De 9 Straatjes"),
    AUSTRALISCH("Australisch"),
    OOSTELIJK_HAVENGEBIED("Oostelijk Havengebied"),
    ZEEHELDEN_KWARTIER("Zeehelden-Kwartier"),
    KRALINGEN_CROOSWIJK("Kralingen/Crooswijk"),
    GROTE_MARKT_HAARLEM("Grote Markt Haarlem"),
    STADSPARK_MAASTRICHT("Stadspark Maastricht"),
    PRACHTIG_UITZICHT("Prachtig uitzicht"),
    NIEUWE_RESTAURANTS("Nieuwe restaurants"),
    WEESPERZIJDE("Weesperzijde"),
    BEZUIDENHOUT_CS("Bezuidenhout/CS"),
    REITDIEPHAVEN("Reitdiephaven"),
    VLEUTEN("Vleuten"),
    RIVIERENWIJK("Rivierenwijk"),
    WITTEVROUWEN("Wittevrouwen"),
    BEATRIX_THEATER("Beatrix Theater"),
    DICHTERSWIJK("Dichterswijk"),
    STATION_UTRECHT_CENTRAAL("Station Utrecht Centraal"),
    ZAKELIJK("Zakelijk"),
    MUSEUMKWARTIER("Museumkwartier"),
    PIJLSWEERD("Pijlswaard"),
    ARTIS("Artis"),
    CENTRAAL_STATION_HAARLEM("Centraal Station Haarlem"),
    NIEUWE_WESTEN("Nieuwe Westen"),
    ITALIAANS("Italiaans"),
    ALEXANDERPOLDER("Alexanderpolder"),
    OUDE_WESTEN("Oude Westen"),
    AMSTERDAM_ZUIDOOST("Amsterdam-Zuidoost"),
    AMSTERDAM_ARENA("Amsterdam Arena"),
    OMMOORD_ZEVENKAMP_NESSELANDE("Ommoord/Zevenkamp/Nesselande"),
    DIM_SUM("Dim sum"),
    AHOY("Ahoy"),
    GRIEKS("Grieks"),
    GROTTEN_ZONNEBERG("Grotten Zonneberg"),
    IJBURG("IJburg"),
    MARIAHOEVE("Mariahoeve"),
    C_S_KWARTIER("C.S. Kwartier"),
    STATIONSBUURT("Stationsbuurt"),
    NEDERLANDS_OPENLUCHTMUSEUM("Nederlands Openluchtmuseum"),
    OUDE_NOORDEN("Oude Noorden"),
    EUROMAST("Euromast"),
    WEST_DELFSHAVEN("West/Delfshaven"),
    BIJLMER("Bijlmer"),
    CENTRAAL_STATION_DEN_BOSCH("Centraal Station Den Bosch"),
    SPAARNDAMMER_EN_ZEEHELDENBUURT("Spaarndammer- en Zeeheldenbuurt"),
    BENOORDENHOUT_CLINGENDAEL("Benoordenhout/Clingendael"),
    KIJKDUIN("Kijkduin"),
    VALKENBOSCH("Valkenbosch"),
    MEZZE("Mezze"),
    STATENKWARTIER("Statenkwartier"),
    PERNIS_HEIJPLAAT("Pernis/Heijplaat"),
    TWEEDE_DAALSEBUURT("Tweede Daalsebuurt"),
    GEZOND("Gezond"),
    OVERVECHT("Overvecht"),
    LOMBOK("Lombok"),
    VOORDORP("Voordorp"),
    FONDUE("Fondue"),
    STERRENWIJK("Sterrenwijk"),
    OP_ZEE("Op zee"),
    NIEUW_ENGLAND("Nieuw England"),
    SCHILDERSWIJK("Schilderswijk"),
    UITHOF("Uithof"),
    ZUIDERPARK("Zuidpark"),
    TWO_MICHELIN_STERREN_2019("2 Michelin Sterren 2019"),
    HOTEL_RESTAURANT("Hotel-restaurant"),
    R_DAM_NOORD("R'dam Noord"),
    MARLOT("Marlot"),
    TOLSTEEG_EN_ROTSOORD("Tolsteeg en Rotsoord"),
    JAPANS("Japans"),
    PROEF_DE_ZOMER("Proef de zomer"),
    HOLLANDS("Hollands"),
    LUNETTEN("Lunetten"),
    SPANGEN("Spangen"),
    OOG_IN_AL("Oog in Al"),
    SPOORWIJK("Spoorwijk"),
    THREE_MICHELIN_STERREN_2019("3 Michelin Sterren 2019"),
    RAW_FOOD("Raw food"),
    BIJZONDER("Bijzonder"),
    TUINDORP("Tuindorp"),
    LAGE_WEIDE("Lage Weide"),
    OP_EEN_BOOT("Op een boot"),
    KIP("Kip"),
    HOOGRAVEN("Hoograven"),
    SCHEPENBUURT("Schepenbuurt"),
    BBQ_GRILL("BBQ/Grill"),
    INTERNATIONAAL("Internationaal"),
    BRUNCH("Brunch"),
    EUROPEES("Europees"),
    ONDIEP("Ondiep")
}